FROM node:13-alpine as builder

WORKDIR /app
COPY . .

EXPOSE 80

RUN apk add --no-cache bash
RUN chmod 755 scripts/*
RUN yarn
RUN yarn build

FROM nginx:alpine

COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]

