name: automerge
on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
  pull_request_review:
    types:
      - approved
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@ccae530ae13b6af67a7a2009c266fe925844e658"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_RETRIES: "12"