name: route-rating-web-app continuous integration
on: [push, pull_request]

env:
  DOCKER_REPO: lukeshaydocker/route-rating-web-app
  SHA: ${GITHUB_SHA::7}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn build
     
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn validate
     
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn test

  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn build
      - run: echo "${secrets.DOCKER_HUB_PASSWORD}" | docker login -u ${secrets.DOCKER_HUB_USERNAME} --password-stdin
      - run: docker build -t ${env.DOCKER_REPO}:${env.SHA} ${env.DOCKER_REPO}:latest .
      - run: docker push ${env.DOCKER_REPO}:${env.SHA}
      - run: test ${github.ref} = "master" && docker push ${env.DOCKER_REPO}:latest || exit 0
