name: route-rating-web-app continuous integration
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn build
     
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn validate
     
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn test