name: route-rating-web-app push to dockerhub
on:
  push:
    branches: [master]

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn build
      - run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.repository }}:${{ github.sha:0:7 }} .
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.repository }}:${{ github.sha:0:7 }}
      - run: docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.repository }}:${{ github.sha:0:7 }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.repository }}:latest
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.repository }}:latest
